name: Scheduled Task

on:
  schedule:
    - cron: "*/10 23,0-17 * * *"
  workflow_dispatch: # 手动触发任务

jobs:
  check-element-job:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.0"

      - name: Install dependencies
        run: pip install requests beautifulsoup4 yagmail

      # 如果文件存在，下载上次上传的 Artifacts
      - name: Download previous artifacts
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: actions/download-artifact@v4
        with:
          name: notice_cache
          path: .

      # 执行脚本
      - name: Run script
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          python main.py

      # 如果文件存在，则上传 Artifacts
      - name: Upload new artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: notice_cache
          path: notice_cache.json
