name: Scheduled Task

on:
  schedule:
    - cron: "*/10 23,0-17 * * *"
  workflow_dispatch: # 手动触发任务

jobs:
  check-element-job:
    # runs-on: self-hosted
    runs-on: ubuntu-22.04
    timeout-minutes: 2 # 超时限制

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        run: |
          echo "Using pre-installed Python"
          python3 --version
          python3 -m pip install --upgrade pip

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.local/lib/python*
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      # 下载上次上传的 Artifacts
      - name: Download artifacts from previous workflow
        uses: dawidd6/action-download-artifact@v7
        continue-on-error: true
        with:
          name: notice_cache
          workflow_conclusion: success
          if_no_artifact_found: warn
          path: .
          search_artifacts: true

      - name: Create default file if not exists
        run: |
          if [ ! -f "notice_cache.json" ] || [ ! -s "notice_cache.json" ]; then
            echo '{}' > notice_cache.json
          fi

      # 执行脚本
      - name: Run script
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        timeout-minutes: 1
        run: |
          python3 main.py

      # 上传 Artifacts
      - name: Upload new artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: notice_cache
          path: notice_cache.json
          retention-days: 1 # 保留 1 天
