name: Scheduled Task

on:
  schedule:
    - cron: "*/10 23,0-17 * * *"
  workflow_dispatch: # 手动触发任务

jobs:
  check-element-job:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.0"
          cache: "pip"

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.local/lib/python3.13/site-packages
          key: pip-${{ runner.os }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      # 下载上次上传的 Artifacts
      - name: Download previous artifacts
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: notice_cache # 改这里：去掉 .json
          path: .

      - name: Create default file if not exists
        run: |
          if [ ! -f notice_cache.json ]; then
            echo '{}' > notice_cache.json
          fi

      # 执行脚本
      - name: Run script
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: |
          python main.py

      # 上传 Artifacts
      - name: Upload new artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: notice_cache
          path: notice_cache.json
          retention-days: 1 # 保留 1 天
